tenancy_ocid        = "ocid1.tenancy.oc1..REPLACE_WITH_YOUR_TENANCY_OCID"
user_ocid           = "ocid1.user.oc1..REPLACE_WITH_YOUR_USER_OCID"
api_fingerprint     = "REPLACE_WITH_YOUR_API_KEY_FINGERPRINT"
api_private_key     = "REPLACE_WITH_YOUR_PEM_PRIVATE_KEY"
availability_domain = "ABcd:EU-FRANKFURT-1-AD-1"
ssh_public_key      = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvQRluXF3TIK00twfnhL1dIS263+JUKXEFh6jV1xuVUFqZMKKyCEoxg+7B1juiUBLETRb1CWcoLMPYZDjyyEheC6LM5rAH2PIBYxujzNx6b82h+NEMEI5mF45HE+NPsnDdOwBTMYFYt0jGOG9/Z5Eqkv0EL5kBX75cvAbATBIVfA8Zocny9mIP/tAFjNQ8hqc+rYnjfrH8ex+p8fREofPARNC7VTPICM7+/ia2h6H/XqFvSxJm7x3pMKbYsbjjduuUIpGK5GzDBKxz+NOZCYHIAwJk1VYa/K/2ZVzqjpTQQapnJ+9GmJHuyuq4qYB/ACPphqInZRjvwG74qEVv9GzvTDH7RmZHj7f2v/XrQ6iA7iB+eJesm5OlJLn29YLwEsOWzgmPIIzkvvF9nviCPxK2zjx0nnJ9/wOEJkxSsT97BhUWWZNnyjgIRMyWQxhPvyQVv1OAeXqJdrLlRO1uC800KSOL/+LHDA5KFRq+0snk5L+P4/sssb9wnhPPBRoi2Is="
database_admin_password = "Password123!"
